using UnityEngine;
using UnityEngine.SceneManagement;

public class LavaRise : MonoBehaviour
{
    public float speed = 0.4f;
    public GameOverManager gameOverManager;

    public bool isActive = false; // lava sÃ³ sobe se estiver ativa

    void Update()
    {
        if (!isActive) return; // Ignora se nÃ£o tiver sido ativada

        transform.position += Vector3.up * speed * Time.deltaTime;
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            Debug.Log("ðŸŒ‹ Jogador tocou na lava!");
            gameOverManager.GameOver();
        }
    }
}